# -*- coding: utf-8 -*-
"""Control Statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y3XOrbnOAsNxQcHsOhAhUTTIgO01_WHI
"""

if 5 > 1:
  print('5 is greater than 1')
  print('Well done')
  print('Hello World')

if 5 < 1:
  print('5 is greater than 1')
  print('Well done')
  print('Hello World')

temp = int(input())
if temp < 15:
  print('Wear a jacket')

x = 5
y = 10
print("hello")
if x < y:
  print("Bye")
print("Hello World")

x = 5
if x == 5:
  x = 7
  print(x)

# what should you write to check if number n is positive?
n = 10
if n > 0:
  print('input number is positive')

temp = int(input())
if temp < 15:
  print( 'wear a jacket')
else:
  print('wear a t-shirt')

# password checker

pass1 = input('enter the password')
pass2 = input('re-enter the password')
if pass1 == pass2:
  print('Password match')
else:
  print('Password mismatch')

x = -15
if x:
  print('True')
else:
  print('false')

# program1
lang = input('enter the favorite programming language')

if lang =='python' or lang =='java':
  print('nice choice')
else:
  if lang == 'c++':
    print('Too old school')
  else:
      print("i don't know that language")

lang = input('enter your favour program')
if lang == 'python' or lang=='java':
  print('Nice Choice')
else:
  if lang == 'golang':
    print("You're awesome")
  else:
      if lang == 'Javascript':
        print('Okay')
      else:
          print("I don't know")

lang = input('enter your favour program')
if lang == 'python' or lang=='java':
  print('Nice Choice')
elif lang== 'golang':
 print("You're awesome")
elif lang == 'Javascript':
  print('Too old')
else:
    print("I don't know")

