# -*- coding: utf-8 -*-
"""python-for-data-engineering/iPhone Data Analysis Mini Project.ipynbipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2kYOMxaK4GhcDOLYPRKG91sMyMXo1ZI
"""

!pip install pyspark py4j
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Basics").getOrCreate()

pip install pandas

import pandas as pd

!pip install google-api-python-client

df = pd.read_csv("apple_products.csv")

df.head(3)

df.count()

df['Mrp'].max()

df['Mrp'].min()

df[df['Mrp']==149900]

df[df['Mrp']==39900]

df[df['Mrp']>=100000]

list(df['Product Name'])[0].upper()

list(df['Product Name'])[0].lower()

list(df['Product Name'])[51][6:15].upper().strip()

df['Model Name'] = df['Product Name'].str[6:15]

df.head()

df.sort_values(by=['Star Rating'], ascending = False)